### PR TITLE
Business profit loss

### PR DESCRIPTION
**Pull request by ushaakumaar**
### Data Retrieval Logic
**business-stock-retrieval.ipynb** - Logic to retrieve the stock data for all NASDAQ tickers into a CSV file in Resources folder
**Resources/stock_data.csv** - Stock data retrieved using Jupyter Notebook Script for all NASDAQ tickers
### Data Analysis Logic
**business-profit-loss.ipynb** - Logic to retrieve the stock data from CSV file into a dataframe.

### CODE REVIEW

**Comment by Prarthna-design** [comment]
I reviewed!

**Review by Prarthna-design — COMMENTED** [review]
Not sure if I was to close the pull request or merge? I closed it

**Comment by Chahnaz-Kbaisi** [comment]
Reviewed!

**Review by SusanCThomas — COMMENTED** [review]
Reviewed!

**Pull request merged**
